name: Publish Dependencies

on:
  registry_package:
    types: [published]

permissions:
  contents: read

jobs:
  trigger:
    name: Build & Publish - ${{ matrix.repo }}
    strategy:
      matrix:
        repo:
#          - Xtate.DataModel.EcmaScript
#          - Xtate.Logger.Serilog
#          - Xtate.IoProcessor.Http
#          - Xtate.IoProcessor.Http.Kestrel
#          - Xtate.Web.Tools
#          - Xtate.Service.HttpClient
#          - Xtate.Service.SmtpClient
#          - Xtate
    
    runs-on: ubuntu-latest
  
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1.2.4
        with:
          workflow: Publish
          token: ${{ secrets.XTATE_GITHUB_TOKEN }}
          repo: TSSArt/${{ matrix.repo }}
          ref: main
